local hall_top_map = require("qnPlist/hall_top");
local hallTopView=
{
	name="hallTopView",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=150,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,stageH=0,
	{
		name="top_view",type=0,typeName="View",time=89202532,x=0,y=0,width=1280,height=150,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
		{
			name="set_btn",type=2,typeName="Button",time=89202541,x=40,y=20,width=80,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=hall_top_map['setBtn.png'],packFile="MahjongPinTu/hall_top.lua",
			{
				name="tip",type=1,typeName="Image",time=91852282,x=45,y=-15,width=39,height=39,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Commonx/tip.png",
				{
					name="Text1",type=4,typeName="Text",time=91852351,x=0,y=-2,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[0]]
				}
			}
		},
		{
			name="help_btn",type=2,typeName="Button",time=89202737,x=126,y=20,width=80,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=hall_top_map['helpBtn.png'],packFile="MahjongPinTu/hall_top.lua",
			{
				name="tip",type=1,typeName="Image",time=91852393,x=45,y=-15,width=39,height=39,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Commonx/tip.png",
				{
					name="Text1",type=4,typeName="Text",time=91852394,x=0,y=-2,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[0]]
				}
			}
		},
		{
			name="message_btn",type=2,typeName="Button",time=89202744,x=212,y=20,width=80,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=hall_top_map['messageBtn.png'],packFile="MahjongPinTu/hall_top.lua",
			{
				name="tip",type=1,typeName="Image",time=91852418,x=45,y=-15,width=39,height=39,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Commonx/tip.png",
				{
					name="Text1",type=4,typeName="Text",time=91852419,x=0,y=-2,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[0]]
				}
			}
		},
		{
			name="first_charge_btn",type=2,typeName="Button",time=89261008,x=304,y=3,width=98,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=hall_top_map['firstChargeIcon.png'],packFile="MahjongPinTu/hall_top.lua"
		},
		{
			name="player_head_view",type=0,typeName="View",time=89261214,x=20,y=0,width=280,height=150,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,
			{
				name="name_bg",type=1,typeName="Image",time=89261511,x=0,y=0,width=252,height=92,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=hall_top_map['userNameBg.png'],packFile="MahjongPinTu/hall_top.lua",
				{
					name="name_text",type=4,typeName="Text",time=89262111,x=5,y=4,width=180,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[ 未登录]],colorA=1
				}
			},
			{
				name="coin_bg",type=1,typeName="Image",time=89262205,x=0,y=56,width=208,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=hall_top_map['coinBg.png'],packFile="MahjongPinTu/hall_top.lua",
				{
					name="money_text",type=4,typeName="Text",time=89262206,x=0,y=0,width=180,height=50,visible=1,fillParentWidth=0,fillParentHeight=1,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=0,string=[[0]]
				},
				{
					name="coin",type=1,typeName="Image",time=89262345,x=0,y=1,width=38,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=hall_top_map['coin.png'],packFile="MahjongPinTu/hall_top.lua"
				}
			},
			{
				name="head_btn",type=2,typeName="Button",time=89262534,x=165,y=6,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Commonx/headBg.png",
				{
					name="head_icon",type=1,typeName="Image",time=89263829,x=0,y=0,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Commonx/blank.png"
				}
			},
			{
				name="diamond_bg",type=1,typeName="Image",time=89262205,x=-174,y=56,width=165,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=hall_top_map['coinBg.png'],packFile="MahjongPinTu/hall_top.lua",
				{
					name="t",type=4,typeName="Text",time=89262206,x=17,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=1,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=0,string=[[0]],colorA=1
				},
				{
					name="diamond",type=1,typeName="Image",time=0,x=-5,y=-2,width=48,height=45,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Commonx/diamond.png"
				}
			},
			{
				name="vip_exp_view",type=0,typeName="View",time=0,x=66,y=100,width=280,height=38,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,
				{
					name="vip_btn",type=1,typeName="Button",time=0,x=0,y=2,width=54,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="Login/oppo/HallTopLayer/vipBtn.png"
				},
				{
					name="vip_img_time",type=1,typeName="Image",time=0,x=56,y=0,width=290,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Login/oppo/HallTopLayer/vip_time_bg.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10,
					{
						name="Text2",type=4,typeName="Text",time=0,x=10,y=0,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=20,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[剩余领取VIP时间:]],colorA=1
					},
					{
						name="Text3",type=4,typeName="Text",time=0,x=168,y=0,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[2小时33分]]
					}
				}
			}
		},
		{
			name="online_view",type=0,typeName="View",time=0,x=370,y=90,width=96,height=101,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="online_reward_btn",type=1,typeName="Button",time=0,x=0,y=0,width=96,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="Login/oppo/HallTopLayer/online_reward_close.png"
			},
			{
				name="online_time_view",type=0,typeName="View",time=0,x=0,y=0,width=96,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,
				{
					name="online_time_bg",type=1,typeName="Image",time=0,x=-6,y=0,width=92,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Login/oppo/HallTopLayer/online_reward_bg.png",
					{
						name="online_time",type=4,typeName="Text",time=0,x=6,y=0,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=18,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[00:00:00]],colorA=1
					}
				}
			}
		}
	}
}
return hallTopView;