local hallContent=
{
	name="hallContent",type=0,typeName="View",time=0,x=60,y=-12,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="bg",type=1,typeName="Image",time=89283818,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=0,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="Hall/hallComon/hallBgMid.jpg"
	},
	{
		name="left",type=1,typeName="Image",time=95225321,x=0,y=0,width=114,height=152,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Hall/hallComon/left.png"
	},
	{
		name="right",type=1,typeName="Image",time=95225335,x=0,y=0,width=91,height=123,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="Hall/hallComon/right.png"
	},
	{
		name="girl",type=1,typeName="Image",time=95225430,x=500,y=0,width=300,height=665,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomLeft,file="Hall/hallComon/girl.png",
		{
			name="face",type=0,typeName="Swf",time=0,x=0,y=0,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,swfFrame=1,swfKeep=0,swfRepeat=-1,swfDelay=0,swfAuto=0,swfAutoClean=0,swfInfoLua="qnSwfRes/hallGirl1_swf_info",swfPinLua="qnSwfRes/hallGirl1_swf_pin"
		},
		{
			name="eye",type=0,typeName="Swf",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,swfFrame=1,swfKeep=0,swfRepeat=-1,swfDelay=0,swfAuto=0,swfAutoClean=0,swfInfoLua="qnSwfRes/hallGirl2_swf_info",swfPinLua="qnSwfRes/hallGirl2_swf_pin"
		},
		{
			name="textBg",type=1,typeName="Image",time=0,x=-45,y=10,width=142,height=114,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="Commonx/paopao.png",
			{
				name="textView",type=5,typeName="TextView",time=0,x=22,y=16,width=100,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=22,textAlign=kAlignLeft,colorRed=234,colorGreen=117,colorBlue=0,colorA=1
			}
		}
	},
	{
		name="main_view",type=0,typeName="View",time=95225433,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
		{
			name="v_1",type=0,typeName="View",time=0,x=60,y=0,width=370,height=430,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,
			{
				name="btn_xzdd",type=2,typeName="Button",time=95225439,x=0,y=-140,width=362,height=134,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="Hall/hallComon/btn_xzdd.png",
				{
					name="swf",type=0,typeName="Swf",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,swfFrame=1,swfKeep=1,swfRepeat=0,swfDelay=0,swfAuto=0,swfAutoClean=0,swfInfoLua="qnSwfRes/hallbuttonFlash1_swf_info",swfPinLua="qnSwfRes/hallbuttonFlash1_swf_pin"
				}
			},
			{
				name="btn_xlch",type=2,typeName="Button",time=95225438,x=0,y=9,width=362,height=118,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="Hall/hallComon/btn_xlch.png",
				{
					name="swf",type=0,typeName="Swf",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,swfFrame=1,swfKeep=1,swfRepeat=0,swfDelay=0,swfAuto=0,swfAutoClean=0,swfInfoLua="qnSwfRes/hallbuttonFlash2_swf_info",swfPinLua="qnSwfRes/hallbuttonFlash2_swf_pin"
				}
			},
			{
				name="btn_match",type=2,typeName="Button",time=95225439,x=0,y=150,width=362,height=134,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="Hall/hallComon/btn_match.png",
				{
					name="swf",type=0,typeName="Swf",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,swfFrame=1,swfKeep=1,swfRepeat=0,swfDelay=0,swfAuto=0,swfAutoClean=0,swfInfoLua="qnSwfRes/hallbuttonFlash1_swf_info",swfPinLua="qnSwfRes/hallbuttonFlash1_swf_pin"
				}
			}
		}
	},
	{
		name="friend_fight",type=1,typeName="Image",time=113559350,x=60,y=0,width=372,height=416,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="Hall/hallComon/btn_bg.png",
		{
			name="btn_addRoom",type=2,typeName="Button",time=113559482,x=0,y=30,width=330,height=164,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="Hall/hallComon/btn_addRoom.png",
			{
				name="swf",type=0,typeName="Swf",time=0,x=198,y=-23,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,swfFrame=1,swfKeep=0,swfRepeat=-1,swfDelay=0,swfAuto=0,swfAutoClean=0,swfInfoLua="qnSwfRes/panda3_swf_info",swfPinLua="qnSwfRes/panda3_swf_pin"
			}
		},
		{
			name="btn_createRoom",type=2,typeName="Button",time=113559553,x=0,y=30,width=330,height=164,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="Hall/hallComon/btn_createRoom.png",
			{
				name="swf",type=0,typeName="Swf",time=0,x=-10,y=-22,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,swfFrame=1,swfKeep=0,swfRepeat=-1,swfDelay=0,swfAuto=0,swfAutoClean=0,swfInfoLua="qnSwfRes/panda4_swf_info",swfPinLua="qnSwfRes/panda4_swf_pin"
			}
		}
	},
	{
		name="btn_more",type=2,typeName="Button",time=113560521,x=0,y=0,width=58,height=156,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="Hall/hallComon/btn_more.png"
	},
	{
		name="surface_view",type=1,typeName="Image",time=114053524,x=0,y=0,width=1280,height=720,visible=0,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="Commonx/zhezhao.png",
		{
			name="v_2",type=0,typeName="View",time=0,x=-390,y=0,width=370,height=430,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,
			{
				name="btn_1",type=1,typeName="Button",time=0,x=0,y=-140,width=364,height=120,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="Hall/hallComon/lfp.png"
			},
			{
				name="btn_2",type=1,typeName="Button",time=0,x=0,y=9,width=364,height=120,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="Hall/hallComon/single.png"
			}
		}
	}
}
return hallContent;