hallLayout_otherVersion=
{
	name="hallLayout_otherVersion",type=0,typeName="View",time=0,x=0,y=0,width=18490208,height=1,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,
	{
		name="bg",type=1,typeName="Image",time=37441422,x=0,y=9,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Common/bg.png",
		{
			name="cj",type=1,typeName="Image",time=39777295,x=0,y=-12,width=800,height=480,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/chunjie.png"
		}
	},
	{
		name="topBar",type=1,typeName="Image",time=37441445,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/topBar.png",packFile="MahjongPinTu/hall_pin.lua",
	},
	{
		name="bottomBar",type=1,typeName="Image",time=37441463,x=0,y=402,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/bottomBar.png",packFile="MahjongPinTu/hall_pin.lua",
		
	},
	{
		name="topViewBar",type=0,typeName="View",time=37441489,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
		{
			name="headbg",type=1,typeName="Image",time=37441490,x=17,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/headBg.png",packFile="MahjongPinTu/hall_pin.lua",
			{
				name="headbg",type=1,typeName="Image",time=37441491,x=11,y=9,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/headIcon.png",packFile="MahjongPinTu/hall_pin.lua"
			},
			{
				name="iconImg",type=2,typeName="Button",time=37441492,x=13,y=11,width=45,height=45,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Common/blank.png"
			}
		},
		{
			name="loginTypeIcon",type=1,typeName="Image",time=37441493,x=90,y=5,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/guest.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="bagBtn",type=2,typeName="Button",time=37441494,x=229,y=-1,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/bag.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="moneyBg",type=1,typeName="Image",time=37441495,x=95,y=33,width=138,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/moneyBg.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="moneyIcon",type=1,typeName="Image",time=37441496,x=90,y=32,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/moneyIcon.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="addMoneyBtn",type=2,typeName="Button",time=37441497,x=216,y=31,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/rechargeMoney.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="moneyText",type=4,typeName="Text",time=37441498,x=114,y=34,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=16,textAlign=kAlignLeft,colorRed=202,colorGreen=202,colorBlue=0,string=[[]]
		},
		{
			name="nameText",type=4,typeName="Text",time=37441499,x=122,y=5,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=20,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[]]
		},
		{
			name="messageBtn",type=2,typeName="Button",time=37441501,x=537,y=12,width=44,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/msgBtn.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="helpBtn",type=2,typeName="Button",time=37441502,x=623,y=11,width=44,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/helpBtn.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="settingBtn",type=2,typeName="Button",time=37441503,x=708,y=15,width=44,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/settingBtn.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="split2",type=1,typeName="Image",time=37441505,x=600,y=12,width=2,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/splite.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="split3",type=1,typeName="Image",time=37441506,x=687,y=12,width=2,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/splite.png",packFile="MahjongPinTu/hall_pin.lua"
		},
	{
		name="cj1",type=1,typeName="Image",time=39777392,x=0,y=290,width=800,height=190,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/chunjie2.png"
	},
		{
			name="returnBtn",type=2,typeName="Button",time=37441507,x=15,y=11,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/back.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="splite",type=1,typeName="Image",time=37441508,x=81,y=8,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/splite.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="titleImg",type=1,typeName="Image",time=37441509,x=333,y=13,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/logo.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="boxTitleImg",type=1,typeName="Image",time=37441510,x=349,y=24,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/boxTitle.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="selectRoomImg",type=1,typeName="Image",time=37441511,x=328,y=24,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/gameRoom.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="showBtnBg",type=1,typeName="Image",time=37441512,x=313,y=8,width=170,height=60,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Common/blank.png",
			{
				name="showFlag",type=1,typeName="Image",time=37441513,x=131,y=23,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/showList.png",packFile="MahjongPinTu/hall_pin.lua"
			}
		},
		{
			name="messageBtn1",type=2,typeName="Button",time=37441515,x=528,y=4,width=60,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Common/blank.png"
		},
		{
			name="helpBtn1",type=2,typeName="Button",time=37441516,x=616,y=4,width=60,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Common/blank.png"
		},
		{
			name="settingBtn1",type=2,typeName="Button",time=37441517,x=704,y=7,width=60,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Common/blank.png"
		}
	},
	{
		name="bottomBarView",type=0,typeName="View",time=37441503,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
		{
			name="taskBtn",type=2,typeName="Button",time=37441504,x=16,y=424,width=111,height=54,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/task.png",packFile="MahjongPinTu/hall_pin.lua",
			{
				name="taskNum",type=1,typeName="Image",time=37441505,x=46,y=-6,width=24,height=24,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="pintu_all/hallPin/tip.png",packFile="MahjongPinTu/hall_pin.lua",
				{
					name="Text1",type=4,typeName="Text",time=37441506,x=0,y=0,width=10,height=10,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=16,textAlign=kAlignLeft,colorRed=255,colorGreen=210,colorBlue=160,string=[[1]]
				}
			}
		},
		{
			name="activityBtn",type=2,typeName="Button",time=37441507,x=180,y=424,width=111,height=54,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/activity.png",packFile="MahjongPinTu/hall_pin.lua",
			{
				name="activityNum",type=1,typeName="Image",time=37441508,x=42,y=-5,width=24,height=24,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="pintu_all/hallPin/tip.png",packFile="MahjongPinTu/hall_pin.lua",
				{
					name="Text2",type=4,typeName="Text",time=37441509,x=0,y=0,width=10,height=10,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=16,textAlign=kAlignLeft,colorRed=255,colorGreen=210,colorBlue=160,string=[[1]]
				}
			}
		},
		{
			name="shopBtn",type=2,typeName="Button",time=37441510,x=342,y=424,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/shop.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="frieadBtn",type=2,typeName="Button",time=37441511,x=506,y=424,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/friend.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="rankBtn",type=2,typeName="Button",time=37441512,x=670,y=424,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/rank.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="split1",type=1,typeName="Image",time=37441513,x=163,y=427,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/splite.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="split2",type=1,typeName="Image",time=37441514,x=321,y=429,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/splite.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="split3",type=1,typeName="Image",time=37441515,x=486,y=428,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/splite.png",packFile="MahjongPinTu/hall_pin.lua"
		},
		{
			name="split4",type=1,typeName="Image",time=37441516,x=646,y=428,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/splite.png",packFile="MahjongPinTu/hall_pin.lua"
		}
	},
	{
		name="diZhuListView",type=0,typeName="View",time=37441521,x=0,y=0,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
		{
			name="listBgImg",type=1,typeName="Image",time=37441522,x=15,y=128,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/box/boxFrame.png"
		},
		{
			name="hideBtn",type=2,typeName="Button",time=37441523,x=182,y=84,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/box/select.png"
		},
		{
			name="shawBtn",type=2,typeName="Button",time=37441524,x=182,y=84,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/box/noSelect.png"
		},
		{
			name="diZhuListBtn",type=1,typeName="Image",time=37441525,x=320,y=86,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/box/selectDi.png",
			{
				name="moneyIcon",type=1,typeName="Image",time=37441526,x=5,y=4,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/box/money.png"
			}
		},
		{
			name="trangelImg",type=1,typeName="Image",time=37441527,x=457,y=95,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/box/showDi.png"
		},
		{
			name="selectDiText",type=4,typeName="Text",time=37441528,x=348,y=91,width=110,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=20,textAlign=kAlignCenter,colorRed=255,colorGreen=200,colorBlue=0,string=[[所有底注]]
		},
		{
			name="refreshBtn",type=2,typeName="Button",time=37441529,x=536,y=80,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/box/refresh.png"
		},
		{
			name="ceateRoomBtn",type=2,typeName="Button",time=37441530,x=640,y=80,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/box/createRoom.png"
		},
		{
			name="hideFullImg",type=1,typeName="Image",time=37441531,x=32,y=92,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/box/hideFull.png"
		},
		{
			name="dizhuImg",type=1,typeName="Image",time=37441532,x=260,y=92,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="newHall/box/dizhu.png"
		}
	}
}
--m_xxreference["D:_Mahjong_SCMahjong_Lua_SCMahjong_Lua_1.6_Resource_scripts_view_SC_800_480_hallLayout_otherVersion.lua"]=1;
