local inviteFriendInFRoom=
{
	name="inviteFriendInFRoom",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,stageW=0,
	{
		name="bg",type=1,typeName="Image",time=112935335,x=0,y=0,width=862,height=544,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Commonx/pop_window_mid.png",
		{
			name="title",type=4,typeName="Text",time=112935396,x=0,y=10,width=0,height=72,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=40,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[邀请好友]]
		},
		{
			name="closeBtn",type=2,typeName="Button",time=112935448,x=-25,y=-25,width=66,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="Commonx/close_btn.png",file2="Commonx/close_btn_disable.png"
		},
		{
			name="split",type=1,typeName="Image",time=0,x=0,y=30,width=2,height=402,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Commonx/split_vert.png"
		},
		{
			name="left",type=0,typeName="View",time=0,x=16,y=80,width=410,height=440,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="title",type=4,typeName="Text",time=0,x=0,y=30,width=100,height=30,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=24,textAlign=kAlignCenter,colorRed=75,colorGreen=43,colorBlue=28,string=[[邀请在线好友]],colorA=1
			},
			{
				name="onlineFriendList",type=0,typeName="ListView",time=0,x=0,y=10,width=410,height=420,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
			},
			{
				name="noFriend",type=4,typeName="Text",time=0,x=0,y=0,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=30,textAlign=kAlignLeft,colorRed=75,colorGreen=43,colorBlue=28,string=[[暂无在线好友]],colorA=1
			}
		},
		{
			name="right",type=0,typeName="View",time=0,x=437,y=80,width=410,height=440,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="title",type=4,typeName="Text",time=0,x=0,y=30,width=100,height=30,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=24,textAlign=kAlignCenter,colorRed=75,colorGreen=43,colorBlue=28,string=[[邀请社交好友]],colorA=1
			},
			{
				name="socialFriendList",type=0,typeName="ListView",time=0,x=0,y=10,width=410,height=420,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
			}
		}
	}
}
return inviteFriendInFRoom;