local layout_veteranPlayerAward=
{
	name="layout_veteranPlayerAward",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="bg",type=1,typeName="Image",time=0,x=61,y=0,width=862,height=544,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Commonx/pop_window_mid.png",
		{
			name="btn_close",type=1,typeName="Button",time=0,x=-15,y=-15,width=66,height=70,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="Commonx/close_btn.png"
		},
		{
			name="title",type=1,typeName="Image",time=0,x=0,y=-57,width=537,height=137,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="veteranPlayerAward/title_1.png"
		},
		{
			name="girl",type=1,typeName="Image",time=0,x=-135,y=-17,width=267,height=551,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="veteranPlayerAward/girl.png"
		},
		{
			name="t",type=4,typeName="Text",time=0,x=120,y=-138,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignLeft,colorRed=92,colorGreen=47,colorBlue=8,string=[[老友好久不见，我们精心为你准备了一份丰厚大礼，欢迎回来！]],colorA=1
		},
		{
			name="v",type=0,typeName="View",time=0,x=120,y=0,width=700,height=184,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,
			{
				name="item_1",type=1,typeName="Image",time=0,x=0,y=0,width=162,height=184,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="veteranPlayerAward/normal.png",
				{
					name="light",type=1,typeName="Image",time=0,x=0,y=0,width=152,height=174,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="veteranPlayerAward/item_light.png"
				},
				{
					name="img",type=1,typeName="Image",time=0,x=0,y=-10,width=124,height=124,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Hall/task/task.png"
				},
				{
					name="tt",type=5,typeName="TextView",time=0,x=0,y=15,width=147,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=22,textAlign=kAlignCenter,colorRed=205,colorGreen=69,colorBlue=0,colorA=1
				},
				{
					name="t",type=4,typeName="Text",time=0,x=0,y=30,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=22,textAlign=kAlignCenter,colorRed=205,colorGreen=69,colorBlue=0,colorA=1
				},
				{
					name="zeng",type=1,typeName="Image",time=0,x=-10,y=-5,width=58,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="veteranPlayerAward/tip.png"
				}
			},
			{
				name="add1",type=1,typeName="Image",time=0,x=157,y=0,width=29,height=29,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="veteranPlayerAward/add.png"
			},
			{
				name="item_2",type=1,typeName="Image",time=0,x=181,y=0,width=162,height=184,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="veteranPlayerAward/orange_bg.png",
				{
					name="light",type=1,typeName="Image",time=0,x=0,y=0,width=152,height=174,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="veteranPlayerAward/item_light.png"
				},
				{
					name="img",type=1,typeName="Image",time=0,x=0,y=-10,width=124,height=124,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Hall/task/task.png"
				},
				{
					name="t",type=4,typeName="Text",time=0,x=0,y=30,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=22,textAlign=kAlignCenter,colorRed=205,colorGreen=69,colorBlue=0,colorA=1
				},
				{
					name="zeng",type=1,typeName="Image",time=0,x=-10,y=-5,width=58,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="veteranPlayerAward/tip.png"
				},
				{
					name="tt",type=5,typeName="TextView",time=0,x=0,y=15,width=147,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=22,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,colorA=1
				}
			},
			{
				name="add2",type=1,typeName="Image",time=0,x=338,y=0,width=29,height=29,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="veteranPlayerAward/add.png"
			},
			{
				name="item_3",type=1,typeName="Image",time=0,x=362,y=0,width=162,height=184,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="veteranPlayerAward/orange_bg.png",
				{
					name="img",type=1,typeName="Image",time=0,x=0,y=-10,width=124,height=124,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Hall/task/task.png"
				},
				{
					name="tt",type=5,typeName="TextView",time=0,x=0,y=15,width=147,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=22,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,colorA=1
				},
				{
					name="t",type=4,typeName="Text",time=0,x=0,y=30,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=22,textAlign=kAlignCenter,colorRed=205,colorGreen=69,colorBlue=0,colorA=1
				},
				{
					name="zeng",type=1,typeName="Image",time=0,x=-10,y=-5,width=58,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="veteranPlayerAward/tip.png"
				}
			},
			{
				name="add3",type=1,typeName="Image",time=0,x=519,y=0,width=29,height=29,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="veteranPlayerAward/add.png"
			},
			{
				name="item_4",type=1,typeName="Image",time=0,x=543,y=0,width=162,height=184,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="veteranPlayerAward/orange_bg.png",
				{
					name="img",type=1,typeName="Image",time=0,x=0,y=-10,width=124,height=124,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Hall/task/task.png"
				},
				{
					name="t",type=4,typeName="Text",time=0,x=0,y=30,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=22,textAlign=kAlignCenter,colorRed=205,colorGreen=69,colorBlue=0,colorA=1
				},
				{
					name="zeng",type=1,typeName="Image",time=0,x=-10,y=-5,width=58,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="veteranPlayerAward/tip.png"
				},
				{
					name="tt",type=5,typeName="TextView",time=0,x=0,y=15,width=147,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=22,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,colorA=1
				}
			}
		},
		{
			name="btn_award",type=1,typeName="Button",time=0,x=0,y=60,width=222,height=74,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="Commonx/yellow_bg_wide_btn.png",
			{
				name="t",type=4,typeName="Text",time=0,x=0,y=-6,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=36,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[领取奖励]],colorA=1
			}
		},
		{
			name="btn_1",type=1,typeName="Button",time=0,x=-150,y=60,width=222,height=74,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="Commonx/yellow_bg_wide_btn.png",
			{
				name="t",type=4,typeName="Text",time=0,x=0,y=-6,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=35,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[去低倍场]],colorA=1
			}
		},
		{
			name="btn_2",type=1,typeName="Button",time=0,x=150,y=60,width=222,height=74,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="Commonx/yellow_bg_wide_btn.png",
			{
				name="t",type=4,typeName="Text",time=0,x=0,y=-6,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=35,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[购 买]],colorA=1
			}
		}
	}
}
return layout_veteranPlayerAward;