local new_braodcast_wnd_layout=
{
	name="new_braodcast_wnd_layout",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
	{
		name="img",type=1,typeName="Image",time=0,x=0,y=5,width=862,height=544,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Hall/broadcast/img.png",
		{
			name="text_img",type=1,typeName="Image",time=0,x=14,y=454,width=648,height=68,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Hall/broadcast/text_bg.png",
			{
				name="img_braodcast",type=1,typeName="Image",time=0,x=14,y=-4,width=100,height=72,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="Hall/broadcast/img_1.png",
				{
					name="t",type=4,typeName="Text",time=0,x=19,y=-23,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=20,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[0]],colorA=1
				}
			},
			{
				name="t",type=4,typeName="Text",time=0,x=0,y=0,width=84,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,fontSize=30,textAlign=kAlignCenter,colorRed=75,colorGreen=43,colorBlue=28,string=[[常用]],colorA=1
			},
			{
				name="edittext",type=6,typeName="EditText",time=0,x=117,y=0,width=442,height=61,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=34,textAlign=kAlignLeft,colorRed=173,colorGreen=158,colorBlue=149,string=[[输入聊天内容]],colorA=1
			}
		},
		{
			name="btn_close",type=2,typeName="Button",time=101533196,x=-24,y=-24,width=66,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="Commonx/close_btn.png",file2="Commonx/close_btn_disable.png"
		},
		{
			name="btn_send",type=1,typeName="Button",time=0,x=690,y=460,width=156,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Commonx/green_small_btn.png",
			{
				name="t",type=4,typeName="Text",time=0,x=0,y=-5,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=36,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[发送]],colorA=1
			}
		},
		{
			name="v_extra",type=0,typeName="View",time=0,x=0,y=0,width=849,height=530,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
			{
				name="zz",type=1,typeName="Image",time=0,x=0,y=0,width=64,height=64,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="Commonx/zhezhao.png"
			},
			{
				name="extra",type=1,typeName="Image",time=0,x=64,y=237,width=722,height=218,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Hall/broadcast/broadcastBg.png",
				{
					name="scrollview",type=0,typeName="ScrollView",time=0,x=0,y=-15,width=679,height=150,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter
				}
			}
		}
	}
}
return new_braodcast_wnd_layout;