local roomResultDetailPin_map = require("qnPlist/roomResultDetailPin");
local resultLayout=
{
	name="resultLayout",type=0,typeName="View",time=0,x=0,y=0,width=1280,height=720,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
	{
		name="bg",type=1,typeName="Image",time=29904932,x=0,y=40,width=860,height=484,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file=roomResultDetailPin_map['lost_bg.png'],packFile="MahjongPinTu/roomResultDetailPin.lua",gridLeft=50,gridRight=50,gridTop=50,gridBottom=50,
		{
			name="close",type=2,typeName="Button",time=39682877,x=-20,y=-20,width=66,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="Commonx/close_btn.png",file2="Commonx/close_btn_disable.png"
		},
		{
			name="listBg",type=1,typeName="Image",time=39680628,x=0,y=72,width=860,height=408,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=roomResultDetailPin_map['lost_bg2.png'],packFile="MahjongPinTu/roomResultDetailPin.lua",gridLeft=30,gridRight=30,gridTop=40,gridBottom=40,
			{
				name="money_bg",type=1,typeName="Image",time=53754439,x=16,y=26,width=828,height=53,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=roomResultDetailPin_map['win_score_bg.png'],packFile="MahjongPinTu/roomResultDetailPin.lua",gridLeft=5,gridRight=5,gridTop=20,gridBottom=20,
				{
					name="splite_line_1",type=1,typeName="Image",time=53754629,x=206,y=1,width=2,height=48,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=roomResultDetailPin_map['win_score_splite_line.png'],packFile="MahjongPinTu/roomResultDetailPin.lua"
				},
				{
					name="splite_line_2",type=1,typeName="Image",time=53754717,x=413,y=1,width=2,height=48,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=roomResultDetailPin_map['win_score_splite_line.png'],packFile="MahjongPinTu/roomResultDetailPin.lua"
				},
				{
					name="splite_line_3",type=1,typeName="Image",time=53754789,x=620,y=1,width=2,height=48,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=roomResultDetailPin_map['win_score_splite_line.png'],packFile="MahjongPinTu/roomResultDetailPin.lua"
				}
			},
			{
				name="money_bg1",type=0,typeName="View",time=53754933,x=14,y=25,width=208,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="money",type=4,typeName="Text",time=29906681,x=0,y=0,width=90,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=255,colorGreen=0,colorBlue=0
				}
			},
			{
				name="money_bg2",type=0,typeName="View",time=53755012,x=222,y=25,width=208,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="money",type=4,typeName="Text",time=53755013,x=0,y=0,width=90,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=255,colorGreen=0,colorBlue=0
				}
			},
			{
				name="money_bg3",type=0,typeName="View",time=53755040,x=429,y=25,width=208,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="money",type=4,typeName="Text",time=53755041,x=0,y=0,width=90,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=148,colorGreen=50,colorBlue=0
				}
			},
			{
				name="money_bg4",type=0,typeName="View",time=53755067,x=636,y=25,width=208,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="money",type=4,typeName="Text",time=53755068,x=0,y=0,width=90,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=148,colorGreen=50,colorBlue=0
				}
			}
		},
		{
			name="again",type=2,typeName="Button",time=53085968,x=160,y=40,width=222,height=74,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="Commonx/green_big_wide_btn.png",
			{
				name="Text1",type=4,typeName="Text",time=53085972,x=0,y=-4,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=36,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[再来一局]]
			}
		},
		{
			name="confirmBtn",type=2,typeName="Button",time=53086058,x=-160,y=40,width=222,height=74,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="Commonx/red_big_wide_btn.png",
			{
				name="name",type=4,typeName="Text",time=53086062,x=0,y=-4,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=36,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255
			}
		},
		{
			name="continueBtn",type=2,typeName="Button",time=79496549,x=0,y=40,width=222,height=74,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="Commonx/green_big_wide_btn.png",
			{
				name="Image1",type=4,typeName="Text",time=96285622,x=0,y=-4,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=36,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[继  续]]
			}
		}
	},
	{
		name="tagBtn1",type=2,typeName="Button",time=29905101,x=226,y=201,width=207,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=roomResultDetailPin_map['win_tab_bg_2.png'],packFile="MahjongPinTu/roomResultDetailPin.lua",gridLeft=31,gridRight=31,
		{
			name="name",type=4,typeName="Text",time=29906534,x=0,y=0,width=18,height=18,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=30,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255
		}
	},
	{
		name="tagBtn2",type=2,typeName="Button",time=29905221,x=433,y=201,width=207,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=roomResultDetailPin_map['win_tab_bg_2.png'],packFile="MahjongPinTu/roomResultDetailPin.lua",gridLeft=31,gridRight=31,
		{
			name="name",type=4,typeName="Text",time=29906549,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=30,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255
		}
	},
	{
		name="tagBtn3",type=2,typeName="Button",time=53068198,x=640,y=201,width=207,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=roomResultDetailPin_map['win_tab_bg_2.png'],packFile="MahjongPinTu/roomResultDetailPin.lua",gridLeft=31,gridRight=31,
		{
			name="name",type=4,typeName="Text",time=29906556,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=30,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255
		}
	},
	{
		name="tagBtn4",type=2,typeName="Button",time=53068227,x=847,y=201,width=207,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=roomResultDetailPin_map['win_tab_bg_2.png'],packFile="MahjongPinTu/roomResultDetailPin.lua",gridLeft=31,gridRight=31,
		{
			name="name",type=4,typeName="Text",time=29906563,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=30,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255
		}
	},
	{
		name="title",type=1,typeName="Image",time=94880921,x=0,y=75,width=479,height=156,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file=roomResultDetailPin_map['title_bg.png'],packFile="MahjongPinTu/roomResultDetailPin.lua",
		{
			name="titleStr",type=1,typeName="Image",time=94880922,x=0,y=-35,width=286,height=158,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file=roomResultDetailPin_map['title_win.png'],packFile="MahjongPinTu/roomResultDetailPin.lua"
		},
		{
			name="firework_2",type=1,typeName="Image",time=94880923,x=-8,y=14,width=132,height=132,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file=roomResultDetailPin_map['firework_2.png'],packFile="MahjongPinTu/roomResultDetailPin.lua"
		},
		{
			name="wind",type=1,typeName="Image",time=94880924,x=0,y=10,width=538,height=168,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file=roomResultDetailPin_map['br_dialog_title_decorate.png'],packFile="MahjongPinTu/roomResultDetailPin.lua"
		},
		{
			name="firework_1",type=1,typeName="Image",time=94880925,x=-5,y=-25,width=141,height=141,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file=roomResultDetailPin_map['firework_1.png'],packFile="MahjongPinTu/roomResultDetailPin.lua"
		}
	}
}
return resultLayout;