local yifriendItem=
{
	name="yifriendItem",type=0,typeName="View",time=0,x=0,y=0,width=1120,height=120,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
	{
		name="item_view",type=0,typeName="View",time=50747657,x=0,y=0,width=1120,height=120,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
		{
			name="img_line",type=1,typeName="Image",time=50809340,x=0,y=0,width=1124,height=116,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="Hall/hallRank/item_bg.png"
		},
		{
			name="nick",type=4,typeName="Text",time=89966438,x=235,y=-4,width=258,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=30,textAlign=kAlignLeft,colorRed=75,colorGreen=43,colorBlue=28,string=[[樱桃小丸子]],colorA=1
		},
		{
			name="coin",type=4,typeName="Text",time=89966440,x=582,y=-4,width=234,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=30,textAlign=kAlignLeft,colorRed=148,colorGreen=50,colorBlue=0,string=[[0000]],colorA=1
		},
		{
			name="view_place",type=0,typeName="View",time=89966445,x=0,y=0,width=110,height=116,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="place_bg",type=1,typeName="Image",time=89966446,x=0,y=0,width=96,height=54,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Hall/hallRank/rank_bg2.png"
			},
			{
				name="Text2",type=4,typeName="Text",time=89966447,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=155,colorGreen=152,colorBlue=145,string=[[未上榜]],colorA=1
			}
		},
		{
			name="head_bg",type=2,typeName="Button",time=89966447,x=115,y=-3,width=90,height=90,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="Hall/hallRank/head_bg.png",
			{
				name="img_photo",type=1,typeName="Image",time=89966448,x=0,y=0,width=2,height=2,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="Commonx/blank.png"
			}
		},
		{
			name="place_img",type=1,typeName="Image",time=0,x=7,y=18,width=90,height=72,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Hall/hallRank/place_1.png"
		},
		{
			name="wealth",type=1,typeName="Image",time=0,x=816,y=39,width=225,height=35,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Hall/hallRank/wealth_level_1.png"
		},
		{
			name="inviteBtn",type=1,typeName="Button",time=0,x=888,y=27,width=156,height=62,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Commonx/yellow_small_btn.png",
			{
				name="Text16",type=4,typeName="Text",time=0,x=27,y=8,width=104,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[邀请]],colorA=1
			}
		},
		{
			name="Image15",type=1,typeName="Image",time=0,x=535,y=39,width=36,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="Hall/hallRank/coin.png"
		}
	}
}
return yifriendItem;