//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_AvatarIKGoalWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.AvatarIKGoal));
		L.RegVar("LeftFoot", get_LeftFoot, null);
		L.RegVar("RightFoot", get_RightFoot, null);
		L.RegVar("LeftHand", get_LeftHand, null);
		L.RegVar("RightHand", get_RightHand, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LeftFoot(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.AvatarIKGoal.LeftFoot);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RightFoot(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.AvatarIKGoal.RightFoot);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LeftHand(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.AvatarIKGoal.LeftHand);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RightHand(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.AvatarIKGoal.RightHand);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.AvatarIKGoal o = (UnityEngine.AvatarIKGoal)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

